[bmscriptsbox]

[bmscriptsbox.info]
id = "7cb5305e-0b5b-405e-a37f-6160ec7ad956"
name = "微信多开"
desc = "Windows微信多开助手脚本 - 一键多开/分身多个微信账号，自动绕过互斥体限制并智能排列窗口，支持快捷键和右键菜单快速启动"
version = "1.0.0"
icon = './imgs/wechat.png'

[bmscriptsbox.runtime]
language = "python"
language_version = ">=3.8"
entry = "main.py"
terminal = "never"

[bmscriptsbox.triggers.context_menu]
enabled = true
targets = ["background"]

[bmscriptsbox.triggers.shortcut]
enabled = true
input_type = ""
